# Generated by Django 2.0.2 on 2018-12-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberpollingrecord',
            options={'verbose_name': '投票记录', 'verbose_name_plural': '投票记录'},
        ),
    ]
