# Generated by Django 2.0.2 on 2018-12-21 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20181220_1002'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='memberpollingrecord',
            name='poll_member_id_90b764_idx',
        ),
        migrations.AddField(
            model_name='memberpollingrecord',
            name='vote_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='投票时间'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='memberpollingrecord',
            index=models.Index(fields=['member', 'polling_activity', 'vote_date', 'vote_item'], name='poll_member_member__ac3c19_idx'),
        ),
    ]
