# Generated by Django 2.0.2 on 2018-05-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='活动名称'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place',
            field=models.CharField(default='', max_length=64, verbose_name='活动地点'),
        ),
    ]
