# Generated by Django 2.0.2 on 2018-12-12 17:15

import appointment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_auto_20181211_1510'),
        ('appointment', '0002_auto_20180526_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeableActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='支付金额')),
                ('out_trade_no', models.CharField(max_length=40, verbose_name='商户订单号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('transaction_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='微信交易单号')),
                ('pay_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='付款时间')),
                ('nonce_str', models.CharField(max_length=40, verbose_name='随机字符串')),
                ('prepay_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('has_created', '已创建'), ('has_paid', '已付款')], default='has_created', max_length=16, verbose_name='订单状态')),
            ],
            options={
                'verbose_name': '收费活动记录',
                'verbose_name_plural': '收费活动记录',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='does_pass',
            field=models.BooleanField(default=True, verbose_name='是否通过'),
        ),
        migrations.AddField(
            model_name='activity',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='收费金额'),
        ),
        migrations.AddField(
            model_name='activity',
            name='rechargeable',
            field=models.BooleanField(default=False, verbose_name='收费活动'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=appointment.models.get_image_path, verbose_name='活动配图'),
        ),
        migrations.AddField(
            model_name='rechargeableactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechargeable_activity', to='appointment.Activity', verbose_name='活动'),
        ),
        migrations.AddField(
            model_name='rechargeableactivity',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechargeable_member', to='me.Member', verbose_name='成员'),
        ),
        migrations.AddIndex(
            model_name='rechargeableactivity',
            index=models.Index(fields=['member', 'activity'], name='appointment_member__a93342_idx'),
        ),
    ]
