# Generated by Django 2.0.2 on 2019-01-24 01:11

import appointment.models
from django.db import migrations, models
import django.db.models.deletion
import utils.global_tools


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0003_auto_20190102_1620'),
        ('appointment', '0004_activity_thumb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityImages',
            fields=[
                ('id', models.CharField(default=utils.global_tools.uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True, verbose_name='上传时间')),
                ('img', models.ImageField(default=None, null=True, upload_to=appointment.models.activity_img_name, verbose_name='活动图片')),
                ('tiny_img', models.ImageField(blank=True, default=None, null=True, upload_to=appointment.models.activity_img_name, verbose_name='缩略图')),
                ('does_exist', models.BooleanField(default=True, verbose_name='是否存在')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acitivty_image', to='appointment.Activity', verbose_name='活动')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_image', to='me.Member', verbose_name='上传者')),
            ],
        ),
    ]
