# Generated by Django 2.0.2 on 2018-05-23 13:10

from django.db import migrations, models
import django.db.models.deletion
import utils.global_tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='比赛时间')),
                ('name', models.CharField(max_length=64, verbose_name='比赛名称')),
                ('project', models.CharField(max_length=8, verbose_name='项目')),
                ('chip_time', models.TimeField(verbose_name='净计时')),
                ('clock_gun_time', models.TimeField(verbose_name='枪声成绩')),
                ('is_pb', models.BooleanField(default=False, verbose_name='是否个人最佳')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marathons', related_query_name='marathon', to='me.Member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '马拉松赛事',
                'verbose_name_plural': '马拉松赛事',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MarathonQueryRecord',
            fields=[
                ('id', models.CharField(default=utils.global_tools.uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('pickled_cookie', models.BinaryField(verbose_name='pickled cookie')),
                ('captcha_img', models.ImageField(default=None, null=True, upload_to='captcha', verbose_name='验证码图片')),
                ('operand1', models.IntegerField(default=None, null=True, verbose_name='操作数1')),
                ('operand2', models.IntegerField(default=None, null=True, verbose_name='操作数2')),
                ('operator', models.CharField(choices=[('+', 'add'), ('-', 'sub'), ('*', 'mul'), ('/', 'div')], default=None, max_length=1, null=True, verbose_name='运算符')),
                ('query_time', models.DateTimeField(auto_now_add=True, verbose_name='查询时间')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marathon_query_records', related_query_name='marathon_query_record', to='me.Member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '马拉松查询记录',
                'verbose_name_plural': '马拉松查询记录',
            },
        ),
        migrations.AddIndex(
            model_name='marathonqueryrecord',
            index=models.Index(fields=['query_time', 'success', 'member'], name='marathon_sp_query_t_227d41_idx'),
        ),
        migrations.AddIndex(
            model_name='marathon',
            index=models.Index(fields=['member'], name='marathon_sp_member__dcaa56_idx'),
        ),
    ]
