# Generated by Django 2.0.2 on 2018-11-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon_spider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marathonqueryrecord',
            name='operand1',
        ),
        migrations.RemoveField(
            model_name='marathonqueryrecord',
            name='operand2',
        ),
        migrations.RemoveField(
            model_name='marathonqueryrecord',
            name='operator',
        ),
    ]
