# Generated by Django 2.0.2 on 2018-11-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon_spider', '0002_auto_20181114_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathonqueryrecord',
            name='pickled_cookie',
            field=models.BinaryField(blank=True, null=True, verbose_name='pickled cookie'),
        ),
    ]
