# Generated by Django 2.0.2 on 2018-12-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon_spider', '0003_auto_20181127_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarathonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=10, verbose_name='选手姓名')),
                ('id_num', models.CharField(max_length=30, verbose_name='身份证号')),
                ('date', models.DateField(verbose_name='比赛时间')),
                ('name', models.CharField(max_length=64, verbose_name='比赛名称')),
                ('project', models.CharField(max_length=8, verbose_name='项目')),
                ('chip_time', models.TimeField(verbose_name='净计时')),
                ('clock_gun_time', models.TimeField(blank=True, default=None, null=True, verbose_name='枪声成绩')),
                ('is_pb', models.BooleanField(default=False, verbose_name='是否个人最佳')),
            ],
            options={
                'verbose_name': '马拉松成绩',
                'verbose_name_plural': '马拉松成绩',
            },
        ),
        migrations.AlterField(
            model_name='marathon',
            name='chip_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='净计时'),
        ),
        migrations.AlterField(
            model_name='marathon',
            name='clock_gun_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='枪声成绩'),
        ),
        migrations.AddIndex(
            model_name='marathondata',
            index=models.Index(fields=['id_num'], name='marathon_sp_id_num_fd1f10_idx'),
        ),
    ]
