# Generated by Django 2.0.2 on 2019-01-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon_spider', '0004_auto_20181221_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='age',
            field=models.IntegerField(choices=[(0, '未知'), (1, '29以下'), (2, '30-34'), (3, '35-39'), (4, '40-44'), (5, '45-49'), (6, '50-54'), (7, '55-59'), (8, '60-64'), (9, '65以上')], default=1, verbose_name='年龄组'),
        ),
        migrations.AddField(
            model_name='marathon',
            name='age_pb',
            field=models.BooleanField(default=False, verbose_name='年龄组PB'),
        ),
        migrations.AddField(
            model_name='marathon',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='marathon',
            name='sex',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='marathondata',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (0, '女')], default=1, verbose_name='性别'),
        ),
    ]
