# Generated by Django 2.0.2 on 2018-11-26 14:50

from django.db import migrations, models
import django.db.models.deletion
import utils.global_tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(default=utils.global_tools.uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='收货人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('province_name', models.CharField(max_length=10, verbose_name='省份')),
                ('city_name', models.CharField(max_length=10, verbose_name='城市')),
                ('county_name', models.CharField(max_length=10, verbose_name='行政区')),
                ('detail_info', models.CharField(max_length=10, verbose_name='详细地址')),
                ('post_num', models.CharField(max_length=10, verbose_name='邮编')),
                ('is_default', models.BooleanField(default=True, verbose_name='是否默认使用')),
                ('does_exist', models.BooleanField(default=True, verbose_name='是否存在')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.CharField(default=utils.global_tools.uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品单价')),
                ('ever_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品原价')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('amount_sold', models.IntegerField(verbose_name='已售')),
                ('amount_remain', models.IntegerField(verbose_name='库存')),
                ('express_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='快递费')),
                ('does_exist', models.BooleanField(default=True, verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='payment/goods/img', verbose_name='商品配图')),
                ('image_ordering', models.IntegerField(verbose_name='图片顺序')),
                ('does_exist', models.BooleanField(default=True, verbose_name='是否使用')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_image', to='pay.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=utils.global_tools.uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('express_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='快递费')),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品总价')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('out_trade_no', models.CharField(max_length=40, verbose_name='商户订单号')),
                ('transaction_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='微信交易单号')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('order_status', models.CharField(choices=[('has_created', '已创建'), ('has_paid', '已付款'), ('has_posted', '已发货')], default='has_created', max_length=16, verbose_name='订单状态')),
                ('nonce_str', models.CharField(max_length=40, verbose_name='随机字符串')),
                ('express_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='快递公司')),
                ('express_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='快递单号')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderaddr_addressid', to='pay.Address', verbose_name='地址id')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_name', to='pay.Goods', verbose_name='商品名称')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_id', to='me.Member', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_id', to='pay.Goods', verbose_name='商品名称')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='pay.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
            },
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['id'], name='pay_goods_id_e1f336_idx'),
        ),
        migrations.AddField(
            model_name='address',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_address', to='me.Member', verbose_name='用户id'),
        ),
        migrations.AddIndex(
            model_name='ordergoods',
            index=models.Index(fields=['goods_id', 'order_id'], name='pay_ordergo_goods_i_194e13_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['id', 'goods_id', 'member_id', 'total_fee', 'out_trade_no', 'nonce_str'], name='pay_order_id_4de9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsimage',
            index=models.Index(fields=['goods_id', 'image_ordering'], name='pay_goodsim_goods_i_a25c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['member_id'], name='pay_address_member__a29ae2_idx'),
        ),
    ]
