# Generated by Django 2.0.2 on 2018-11-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepay_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
