# Generated by Django 2.0.2 on 2018-11-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_deliveryrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='detail_info',
            field=models.CharField(max_length=50, verbose_name='详细地址'),
        ),
    ]
