# Generated by Django 2.0.2 on 2018-12-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_auto_20181130_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_detail',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='具体地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='收货人'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='联系方式'),
        ),
    ]
