# Generated by Django 2.0.2 on 2018-12-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0006_auto_20181211_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=10, verbose_name='省份')),
                ('price', models.IntegerField(verbose_name='首重')),
            ],
            options={
                'verbose_name': '快递费',
                'verbose_name_plural': '快递费',
            },
        ),
    ]
