# Generated by Django 2.0.2 on 2019-01-02 16:16

from django.db import migrations, models
import django.db.models.deletion
import utils.global_tools


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_auto_20181211_1510'),
        ('pay', '0007_expressprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountSteps',
            fields=[
                ('id', models.CharField(default=utils.global_tools.uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('total_steps', models.IntegerField(default=0, verbose_name='当月总步数')),
                ('today_steps', models.IntegerField(default=0, verbose_name='今日步数')),
                ('last_count', models.IntegerField(default=0, verbose_name='最后一次同步的时间')),
            ],
            options={
                'verbose_name': '月赛计步',
                'verbose_name_plural': '月赛计步',
            },
        ),
        migrations.AddIndex(
            model_name='expressprice',
            index=models.Index(fields=['province'], name='pay_express_provinc_37e1a6_idx'),
        ),
        migrations.AddField(
            model_name='countsteps',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_count_steps', to='me.Member', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='countsteps',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_count_steps', to='pay.Order', verbose_name='订单'),
        ),
        migrations.AddIndex(
            model_name='countsteps',
            index=models.Index(fields=['order'], name='pay_countst_order_i_844092_idx'),
        ),
    ]
