# Generated by Django 2.0.2 on 2019-01-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_auto_20181211_1510'),
        ('association', '0003_auto_20181214_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchFundRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='贡献额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('out_trade_no', models.CharField(blank=True, max_length=40, null=True, verbose_name='商户订单号')),
                ('transaction_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='微信交易单号')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('order_status', models.CharField(choices=[('has_created', '已创建'), ('has_paid', '已付款'), ('has_posted', '已发货')], default='has_created', max_length=16, verbose_name='订单状态')),
                ('nonce_str', models.CharField(blank=True, max_length=40, null=True, verbose_name='随机字符串')),
                ('prepay_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': '分舵基金记录',
                'verbose_name_plural': '分舵基金记录',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='分舵基金'),
        ),
        migrations.AddField(
            model_name='branchfundrecord',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_fund', to='association.Branch', verbose_name='所属分舵'),
        ),
        migrations.AddField(
            model_name='branchfundrecord',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_branch_fund', to='me.Member', verbose_name='贡献成员'),
        ),
        migrations.AddIndex(
            model_name='branchfundrecord',
            index=models.Index(fields=['branch'], name='association_branch__5a583f_idx'),
        ),
    ]
