# Generated by Django 2.0.2 on 2018-05-23 13:10

from django.db import migrations, models
import running.models
import utils.global_tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.CharField(default=utils.global_tools.uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=64, verbose_name='赛事名称')),
                ('sign_up_date', models.DateField(blank=True, null=True, verbose_name='报名日期')),
                ('deadline_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='赛事开始日期')),
                ('image', models.ImageField(default=None, null=True, upload_to=running.models.get_image_path, verbose_name='赛事配图')),
                ('status', models.CharField(choices=[('has_completed', '已结束'), ('is_signing_up', '报名中'), ('does_not_open', '未开启')], default='does_not_open', max_length=16, verbose_name='赛事状态')),
                ('detail', models.TextField(default='', verbose_name='赛事详情')),
                ('followers', models.ManyToManyField(editable=False, related_name='followed_races', related_query_name='followed_race', to='me.Member', verbose_name='关注者')),
            ],
            options={
                'verbose_name': '赛事',
                'verbose_name_plural': '赛事',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['id', 'status'], name='running_rac_id_2d02b6_idx'),
        ),
    ]
