# Generated by Django 2.0.2 on 2019-03-19 03:34

from django.db import migrations, models
import django.db.models.deletion
import ourRace.models
import utils.global_tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('me', '0003_auto_20190102_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionEvent',
            fields=[
                ('id', models.CharField(default=utils.global_tools.uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=64, verbose_name='竞赛项目名称')),
                ('length', models.CharField(default='', max_length=32, verbose_name='里程长度')),
                ('route', models.TextField(default='', verbose_name='路线')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='报名费用')),
            ],
            options={
                'verbose_name': '竞赛项目',
                'verbose_name_plural': '竞赛项目',
            },
        ),
        migrations.CreateModel(
            name='CompetitionEventParticipationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(default='', max_length=32, verbose_name='团报分舵id')),
                ('marathon_id', models.CharField(default='', max_length=32, verbose_name='马拉松id')),
                ('in_time', models.DateTimeField(auto_now_add=True, verbose_name='参与时间')),
                ('pay_status', models.BooleanField(default=False, verbose_name='是否付款')),
                ('prepay_id', models.CharField(default='', max_length=50, verbose_name='预支付交易会话标识')),
                ('out_trade_no', models.CharField(default='', max_length=40, verbose_name='商户订单号')),
                ('nonce_str', models.CharField(default='', max_length=40, verbose_name='随机字符串')),
            ],
            options={
                'verbose_name': '马拉松赛事参与记录',
                'verbose_name_plural': '马拉松赛事参与记录',
            },
        ),
        migrations.CreateModel(
            name='Marathon',
            fields=[
                ('id', models.CharField(default=utils.global_tools.uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=64, verbose_name='赛事名称')),
                ('status', models.CharField(choices=[('is_signing_up', '报名中'), ('has_completed', '已结束')], default='is_signing_up', max_length=16, verbose_name='赛事状态')),
                ('sign_up_begin', models.DateTimeField(verbose_name='报名开始时间')),
                ('sign_up_end', models.DateTimeField(verbose_name='报名结束时间')),
                ('time', models.DateTimeField(verbose_name='比赛开始时间')),
                ('place', models.CharField(default='', max_length=64, verbose_name='赛事地点')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=ourRace.models.get_marathon_image_path, verbose_name='赛事图片')),
            ],
            options={
                'verbose_name': '赛事信息',
                'verbose_name_plural': '赛事信息',
            },
        ),
        migrations.CreateModel(
            name='MarathonInfo',
            fields=[
                ('id', models.CharField(default=utils.global_tools.uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=64, verbose_name='章程名称')),
                ('sponsor', models.TextField(default='', verbose_name='主办运营单位')),
                ('organizer', models.TextField(default='', verbose_name='承办运营单位')),
                ('method_of_competition', models.TextField(default='', verbose_name='竞赛办法')),
                ('method_of_join', models.TextField(default='', verbose_name='参赛办法')),
                ('method_of_reward', models.TextField(default='', verbose_name='奖励办法')),
                ('method_of_punishment', models.TextField(default='', verbose_name='处罚办法')),
                ('insurance', models.TextField(default='', verbose_name='保险')),
                ('contact_way', models.TextField(default='', verbose_name='联系方式')),
            ],
            options={
                'verbose_name': '赛事章程',
                'verbose_name_plural': '赛事章程',
            },
        ),
        migrations.CreateModel(
            name='ParticipationInfo',
            fields=[
                ('id', models.CharField(default=utils.global_tools.uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=32, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女'), ('0', '未知')], default='0', max_length=1, verbose_name='性别')),
                ('certificate_type', models.CharField(choices=[('0', '身份证'), ('1', '护照'), ('2', '军人证')], default='0', max_length=10, verbose_name='证件类型')),
                ('certificate_num', models.CharField(default='', max_length=32, verbose_name='证件号')),
                ('birthday', models.CharField(default='', max_length=32, verbose_name='生日')),
                ('national', models.CharField(default='', max_length=32, verbose_name='民族')),
                ('email', models.CharField(default='', max_length=20, verbose_name='邮箱')),
                ('mobile', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O'), ('N', '其他')], default='N', max_length=2, verbose_name='血型')),
                ('emergency_contact', models.CharField(default='', max_length=32, verbose_name='紧急联系人')),
                ('emergency_contact_mobile', models.CharField(default='', max_length=11, verbose_name='紧急联系人电话')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.Member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '报名信息',
                'verbose_name_plural': '报名信息',
            },
        ),
        migrations.AddIndex(
            model_name='marathoninfo',
            index=models.Index(fields=['id', 'name'], name='ourRace_mar_id_b3e217_idx'),
        ),
        migrations.AddField(
            model_name='marathon',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race', to='ourRace.MarathonInfo', verbose_name='赛事章程'),
        ),
        migrations.AddField(
            model_name='competitioneventparticipationrecord',
            name='competition_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_event_participation_records', related_query_name='competition_event_participation_record', to='ourRace.CompetitionEvent', verbose_name='竞赛项目'),
        ),
        migrations.AddField(
            model_name='competitioneventparticipationrecord',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marathon_participation_records', related_query_name='marathon_participation_record', to='me.Member', verbose_name='成员'),
        ),
        migrations.AddField(
            model_name='competitionevent',
            name='marathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_events', to='ourRace.Marathon', verbose_name='所从属马拉松赛事'),
        ),
        migrations.AddIndex(
            model_name='participationinfo',
            index=models.Index(fields=['id', 'member'], name='ourRace_par_id_0d5f70_idx'),
        ),
        migrations.AddIndex(
            model_name='marathon',
            index=models.Index(fields=['id', 'name', 'status'], name='ourRace_mar_id_65c604_idx'),
        ),
        migrations.AddIndex(
            model_name='competitioneventparticipationrecord',
            index=models.Index(fields=['member', 'competition_event', 'out_trade_no'], name='ourRace_com_member__3bf3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionevent',
            index=models.Index(fields=['id', 'marathon', 'name'], name='ourRace_com_id_332a89_idx'),
        ),
    ]
