# Generated by Django 2.0.2 on 2018-05-23 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import utils.global_tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(default=utils.global_tools.uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=28, unique=True, verbose_name='微信openid')),
                ('wx_session_key', models.CharField(max_length=128, verbose_name='微信session_key')),
                ('token_hash', models.CharField(max_length=32, verbose_name='用户token的加盐哈希')),
                ('salt', models.CharField(max_length=32, verbose_name='盐')),
                ('last_login', models.DateTimeField(default=datetime.datetime.now, verbose_name='上一次调用微信认证的时间')),
                ('name', models.CharField(default='', max_length=32, verbose_name='用户名称')),
                ('avatar_url', models.URLField(default='', verbose_name='用户头像URL')),
                ('mobile', models.CharField(default='', max_length=11, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
                'ordering': ['-last_login'],
            },
        ),
        migrations.CreateModel(
            name='CheckMobile',
            fields=[
                ('mobile', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('verification_code', models.PositiveIntegerField(default=utils.global_tools.random_int_6, verbose_name='验证码')),
                ('expire', models.DateTimeField(default=utils.global_tools.ten_minutes_from_now, verbose_name='过期时间')),
                ('counter', models.SmallIntegerField(default=0, verbose_name='调用次数')),
                ('limit_time', models.DateTimeField(default=None, null=True, verbose_name='上一次达到验证上限的时间')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='check_mobile', related_query_name='check_mobile', serialize=False, to='me.Member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女'), ('0', '未知')], default='0', max_length=1, verbose_name='用户性别')),
                ('city', models.CharField(default='', max_length=32, verbose_name='用户所在城市')),
                ('province', models.CharField(default='', max_length=16, verbose_name='用户所在省份')),
                ('country', models.CharField(default='', max_length=16, verbose_name='用户所在国家')),
                ('language', models.CharField(default='zh_CN', max_length=8, verbose_name='用户语言')),
                ('marathon_id_num', models.CharField(default='', max_length=32, verbose_name='马拉松证件号')),
                ('real_name', models.CharField(default='', max_length=8, verbose_name='真实姓名')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='member_profile', related_query_name='member_profile', serialize=False, to='me.Member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '成员信息',
                'verbose_name_plural': '成员信息',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='deputy_of',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputies', related_query_name='deputy', to='association.Branch', verbose_name='是副舵主'),
        ),
        migrations.AddField(
            model_name='member',
            name='master_of',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master', related_query_name='master', to='association.Branch', verbose_name='是舵主'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_of',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', related_query_name='member', to='association.Branch', verbose_name='是分舵参与者'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['member'], name='me_memberpr_member__7ab1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['id', 'openid', 'last_login', 'master_of', 'deputy_of', 'member_of'], name='me_member_id_c0bc97_idx'),
        ),
        migrations.AddIndex(
            model_name='checkmobile',
            index=models.Index(fields=['member'], name='me_checkmob_member__b6ba4b_idx'),
        ),
    ]
