# Generated by Django 2.0.2 on 2018-12-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberFormId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formid', models.CharField(max_length=50)),
                ('timestamp', models.IntegerField(verbose_name='失效时间戳')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name': 'FormId',
                'verbose_name_plural': 'FormId',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='wx_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memberformid',
            name='member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_formid', related_query_name='member_formids', to='me.Member', verbose_name='成员'),
        ),
        migrations.AddIndex(
            model_name='memberformid',
            index=models.Index(fields=['member', 'timestamp', 'is_available'], name='me_memberfo_member__763b7f_idx'),
        ),
    ]
